In [2]:
import tensorflow as tf

with tf.Graph().as_default():
  # Create a six-element vector (1-D tensor).
  primes = tf.constant([2, 3, 5, 7, 11, 13], dtype=tf.int32)

  # Create another six-element vector. Each element in the vector will be
  # initialized to 1. The first argument is the shape of the tensor (more
  # on shapes below).
  ones = tf.ones([6], dtype=tf.int32)

  # Add the two vectors. The resulting tensor is a six-element vector.
  just_beyond_primes = tf.add(primes, ones)

  # Create a session to run the default graph.
  with tf.Session() as sess:
    print just_beyond_primes.eval()
    
    
with tf.Graph().as_default():
  # A scalar (0-D tensor).
  scalar = tf.zeros([])

  # A vector with 3 elements.
  vector = tf.zeros([3])

  # A matrix with 2 rows and 3 columns.
  matrix = tf.zeros([2, 3])

  with tf.Session() as sess:
    print 'scalar has shape', scalar.get_shape(), 'and value:\n', scalar.eval()
    print 'vector has shape', vector.get_shape(), 'and value:\n', vector.eval()
    print 'matrix has shape', matrix.get_shape(), 'and value:\n', matrix.eval()


[ 3  4  6  8 12 14]
scalar has shape () and value:
0.0
vector has shape (3,) and value:
[ 0.  0.  0.]
matrix has shape (2, 3) and value:
[[ 0.  0.  0.]
 [ 0.  0.  0.]]


Note : Below is a sample of broadcasting. Instead of using an array to add to array, you can just create a constant and "broadcast" the value to the array. In this case, addition.

In [3]:
# Broadcasting

with tf.Graph().as_default():
  # Create a six-element vector (1-D tensor).
  primes = tf.constant([2, 3, 5, 7, 11, 13], dtype=tf.int32)

  # Create a constant scalar with value 1.
  # Note : Unlike the previous sample, this is just 1 0d array -- meaning a constant
  ones = tf.constant(1, dtype=tf.int32)

  # Add the two tensors. The resulting tensor is a six-element vector. 
  # Note : The variable ones in broadcased
  just_beyond_primes = tf.add(primes, ones)

  with tf.Session() as sess:
    print just_beyond_primes.eval()

[ 3  4  6  8 12 14]


Matrix Multiplication sample

Note : Algebra rule - The column of the first matrix, must be equal to the row of the second matrix

x = first matrix [[5, 2, 4, 3], [5, 1, 6, -2], [-1, 3, -1, -2]]
y = second matrix [[2, 2], [3, 5], [4, 5], [1, 6]]

How?!?

If we multiply a 2×3 matrix with a 3×1 matrix, the product matrix is 2×1
product of two matrices general example

Here is how we get M11 and M12 in the product.
M11 = r11× t11  +  r12× t21  +   r13×t31
M12 = r21× t11  +  r22× t21   +  r23×t31

Read more: http://www.mathwarehouse.com/algebra/matrix/multiply-matrix.php#ixzz5HM7skgxJ

In [4]:
with tf.Graph().as_default():
  # Create a matrix (2-d tensor) with 3 rows and 4 columns.
  x = tf.constant([[5, 2, 4, 3], [5, 1, 6, -2], [-1, 3, -1, -2]],
                  dtype=tf.int32)

  # Create a matrix with 4 rows and 2 columns.
  y = tf.constant([[2, 2], [3, 5], [4, 5], [1, 6]], dtype=tf.int32)

  # Multiply `x` by `y`. 
  # The resulting matrix will have 3 rows and 2 columns.
  matrix_multiply_result = tf.matmul(x, y)

  with tf.Session() as sess:
    print matrix_multiply_result.eval()

[[35 58]
 [35 33]
 [ 1 -4]]
